### ISSUE TITLE
Generated purls not compatible with OSS analysis in Dependency-track

### ISSUE THREAD

**Issue by ddresser** [CycloneDX/cyclonedx-buildroot#12]
First of all, thanks for providing this tool.

Using this tool, I generated a CycloneDX SBOM and posted it to OWASP Dependency-track.  It was ingested and showed the expected components, but I got no vulnerability data from either the internal (uses CPE) or Sonatype OSS (uses pURL) analyzers. What I discovered is that this tool generates a pURL, but it isn't compatible with the OSS analyzer lookup.  It doesn't generate a CPE that could be used by the internal Dependency-track analyzer.

I provided more details in this stackoverflow question.

https://stackoverflow.com/questions/76574392/is-cyclonedx-buildroot-expected-to-generate-compatible-sboms-for-dependency-trac

So currently, the tool is useful for generating an SBOM that can work with Dependency-track to provide an inventory, but is not useful for vulnerability analysis in Dependency-track.

It would be excellent if the tool could generate CycloneDX SBOMs that are compatible with the vulnerability analyzers in OWASP Dependency-track by either generating a compatible pURL or a CPE.

**Comment by ptdropper** [comment]
I recognize that there is a large difference in the URL data produced by Buildroot and the capabilities of other tools including CycloneDX, so I am facing limitations that are built-in. Please recognize that Buildroot itself is a package manager for embedded products. 
From my perspective the url in the above format (pkg:generic/busybox@1.35.0?download_url=https://www.busybox.net/downloadsbusybox-1.35.0.tar.bz2) is exactly what I can parse from the Buildroot manifest file. 
I do not use Sonatype so no comment possible there. If you have several examples of what would work please provide. Please check with Sonatype that it is capable of handling the types of packages used in the embedded world. I cannot know if that is possible. I use Timesys Vigiles to manage vulnerability analysis. 
The Buildroot embedded projects do not use RPM package management but rather use Buildroot for package management. 
This will be a feature request. Thanks! https://github.com/CycloneDX/cyclonedx-buildroot/issues/12

**Comment by ptdropper** [comment]
Buildroot itself is a package manager for embedded projects that use open source software. So it may be that Sonatype does not support Buildroot's pURL data.

**Comment by jkowalleck** [comment]
- Sonatype OSS (uses pURL) 
- pURL does not recognixe `buildroot` - see https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#other-candidate-types-to-define
- Sonatype OSS Index does not know `buildroot` - see https://ossindex.sonatype.org/ecosystems 

so i would question the feature request.

**Comment by ddresser** [comment]
Thanks for the responses.  I'm just learning about this stuff.  What I am trying to accomplish is to get valid CVE lookups on my CycloneDX SBOMs via Dependency-track.  The "internal" analyzer in dependency-track uses the Common Platform Enumeration (CPE) for lookups instead of the pURL.  A valid CPE for busybox is

- cpe:2.3:a:busybox:busybox:1.35.0:*:*:*:*:*:*:*

It looks like the required data is available to generate the CPE.  Perhaps the feature request should be to add the CPE to the SBOM.

We also currently use Timesys Vigiles for our Buildroot builds.  Interestingly if you export a CycloneDX SBOM from Vigiles, it contains the CPE.

Thanks again for your help.

**Comment by ptdropper** [comment]
I may go down the route of CPE or proper pURL based on the feature request you provided. I have not decided. The pURL requires me to do work in the Cyclone DX purl project because the feature is not yet available. Now you can see the lack of support for Buildroot, and my desire to make it happen.
I also use Vigiles and the Vigiles CycloneDX output format works as an input to Depdendency Track. However there are limits. We have a huge collection of data in Vigiles that it labels as "Whitelist" information. The whitelist justification data is not exported in either the CycloneDX or SPDX output formats. I put in a request to Timesys for that feature. I ask you to do the same so they see the need.

**Comment by ptdropper** [comment]
Feature implementation is underway. Testing is promising.

**Comment by ddresser** [comment]
Wanted to say thanks for implementing cpe support.  I just tested it in my workflow and the cpe is recognized and analyzed by OWASP Dependency-Track.  Thank you!

**Comment by ptdropper** [comment]
I put on version 1.0.7 to correctly form the values of the component
license. The previous versions were producing a license object that was not
following the cyclone DX specification property. One of my team members at
work discovered this problem when they attempted to import the output from
my project and the other project refused it indicating an error. Here error
has been corrected. Give it a try.

Robert Smigielski
