### ISSUE TITLE
Output export json doesn't seem to be a valid BOM

### ISSUE THREAD

**Issue by arthurep** [CycloneDX/cyclonedx-buildroot#2]
First of all I'd like to thank you for this project. It seems this is only available option to easily get a BOM from a buildroot environment. 

I'm aware that this project is in its very early stage so I assume lot of things might not work well, yet I'd like to give it a shot to make it work.

After running `python3 generateBuildrootSBOM.py -i manifest.csv -it csv` using the `manifest.csv` generated from buildroot's `make legal-info`, I take the `export` output json and attempt to validate it via the `cyclonedx-cli`:
```
❯ cyclonedx validate --input-file export --input-format json --input-version v1_4
Validating JSON BOM...
Validation failed: 
#/properties
BOM is not valid.
```

FYI I have installed `cyclonedx-python-lib 4.0.0` in my system and I am using the `cyclonedx-cli 0.24.2`

I was also able to reproduce the same issue using the `manifest.csv` from a recent buildroot tag default configuration:
``` 
git clone https://github.com/buildroot/buildroot.git
cd buildroot
git checkout 2023.02
make defconfig
make legal-info
```

Let me know if there's anything else I can provide. Thanks!

**Comment by arthurep** [comment]
No problem. Glad to help :)

I have found the issues with the SBOM format. Here's a comparison with the official cycloneDX SBOM 1.4 Schema:
https://www.jsonschemavalidator.net/s/LmSBLlRk

You can see there are a minor issues with it. Since they were simple fixes, I took the liberty to make a pull request to fix these: https://github.com/CycloneDX/cyclonedx-buildroot/pull/3

**Comment by ptdropper** [comment]
Fixed. I put out a new tag called v1.0 to provide json and xml output from the Buildroot manifest.csv. The command line accepts the name of your Buildroot project and the version you assign to your Buildroot project.
