### ISSUE TITLE
make_with_license dependency breaking change

### ISSUE THREAD

**Issue by k17trmeye** [CycloneDX/cyclonedx-buildroot#37]
With LicenseChoiceFactory class removed from license.py, the script generateBuildrootSBOM.py is not working as it utilizes the "make_with_license" function within LicenseChoiceFactory class.

**Comment by ptdropper** [comment]
That used to work, I suspect a dependency issue. Will check on this, however work pressure is extreme for project delivery so I have little time to look.

**Comment by ptdropper** [comment]
My suspicion is that the dependency on the Cyclonedx Python library cyclonedx-python-lib = "^4.1" should be changed from "^4.1" to exactly 4.1 in the file pyproject.toml at line 15. I have not tried it but I know for certain that the make_with_license is a function in that library. If you would like to try on your local build environment and let me know. I can give it a try once I get back to my development machine at home.

**Comment by ptdropper** [comment]
Tracking the facts: 
https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/CHANGELOG.md
BREAKING CHANGES
Dropped support for python<3.8 (https://github.com/CycloneDX/cyclonedx-python-lib/issues/436 via https://github.com/CycloneDX/cyclonedx-python-lib/pull/441; enable https://github.com/CycloneDX/cyclonedx-python-lib/pull/433)
Reworked license related models, collections, and factories (https://github.com/CycloneDX/cyclonedx-python-lib/issues/365 via https://github.com/CycloneDX/cyclonedx-python-lib/pull/466)
