### ISSUE TITLE
Create test cases

### ISSUE THREAD

**Issue by ptdropper** [CycloneDX/cyclonedx-buildroot#4]
given a fixed input file test that the output data is valid

**Comment by jkowalleck** [comment]
> given a fixed input file test that the output data is ~~valid~~ as expected

**Comment by ptdropper** [comment]
Update for today includes unit tests using the python "unittest" module. Will continue to add test cases over time.

**Comment by ptdropper** [comment]
Test cased implemented July 2023. Closing
