### ISSUE TITLE
cpe-id not found in pkg-stats.json

### ISSUE THREAD

**Issue by bacherd** [CycloneDX/cyclonedx-buildroot#41]
I generate the pkg-stats.json file with make pkg-stats:
```json
{
  "packages": {
    "grub2": {
      ...
      "url": "http://www.gnu.org/software/grub/",
      "cpeid": "cpe:2.3:a:gnu:grub2:2.12:*:*:*:*:*:*:*",
      ...
  },
 "stats": {
    ...
    "cpe-id": 54,
    ...
  },
  ...
}
```
If I understand the code correctly, it is looking for a field called cpe-id, but the field is called cpeid. I have built a workaround to find the cpeid again

```python
   try:
      # FIXME: oiginal code does not work with the current (2024.08) buildroot version.
      if sw_component_name in cpe_value:                
         sw_object = cpe_value[sw_component_name]
         retval = sw_object['cpeid']
         cpe_file.close()
         return retval
   except:  # Some entries do not have a "name" key and no "cpe-id" so skip these.
      pass
```

**Comment by ptdropper** [comment]
This looks like a change in buildroot that means the code may need to support both spellings.

**Comment by ptdropper** [comment]
The README indicates the code works and is tested with the use of the buildroot target "make show-info", in the command line option: 
-c <path> - cpe file name from make show-info, example cpe.json
Thus this issue is a new feature to support the target ""make pkg-stats"

**Comment by ptdropper** [comment]
@bacherd  Hi - I have a proposed solution in the pull request https://github.com/CycloneDX/cyclonedx-buildroot/pull/42
Would you be able to take a look for me?

**Comment by bacherd** [comment]
@ptdropper Hi, it looks good to me. I also tested your branch with my build and it works for me. Thanks for the new feature.
