### ISSUE TITLE
define python requirements and dependencies

### ISSUE THREAD

**Issue by ptdropper** [CycloneDX/cyclonedx-buildroot#5]
gather the requirements/dependnecies (libraries, system, env)

**Comment by jkowalleck** [comment]
1. move the exsiting <https://github.com/CycloneDX/cyclonedx-buildroot/blob/8f44f54306cd30df1ece6487494364bec56e882e/docs/requirements.txt>
to the porject root dir.
2. remove transitive dependencies from the `requirements.txt`

**Comment by ptdropper** [comment]
I pushed branch "documentation" with the change, Please review,
https://github.com/CycloneDX/cyclonedx-buildroot/commit/f7e29498762ec6d23fdf87ace847a0dcfa6559a3

**Comment by ptdropper** [comment]
requirements.txt moved too root directory and pyproject.toml removed in pull request Project documentation #7

**Comment by jkowalleck** [comment]
current `requirements.txt` lists 
```text
cyclonedx-bom==3.11.0
cyclonedx-python-lib==3.1.5
packageurl-python==0.11.1
packaging==23.1
pip-requirements-parser==32.0.1
pyparsing==3.0.9
sortedcontainers==2.4.0
toml==0.10.2
```

i'd say the only thngs you actually need are 
* `packageurl-python` 
* `cyclonedx-python-lib` 

`cyclonedx-bom` is a programm, not a library.
the rest seams to be transitive dependencies that are already managed by the required libraries.
