### ISSUE TITLE
docs: fix readme

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-buildroot#6]
readme is wrong: 

- it speaks of a plugin, but this project is an executable
  https://github.com/CycloneDX/cyclonedx-buildroot/blob/8f44f54306cd30df1ece6487494364bec56e882e/README.md#L12  
- the usage is just wrong -- it does not call this project but something else
  https://github.com/CycloneDX/cyclonedx-buildroot/blob/8f44f54306cd30df1ece6487494364bec56e882e/README.md#L25

**Comment by ptdropper** [comment]
Making the updates this evening. I inherited the README.md contents from the previous project maintainer, so I will fix it up.

**Comment by ptdropper** [comment]
Branch "documentation" pushed for your review. https://github.com/CycloneDX/cyclonedx-buildroot/commit/f7e29498762ec6d23fdf87ace847a0dcfa6559a3
I broke the executable so I am working on a correction

**Comment by jkowalleck** [comment]
i'd suggest fixing docs only and merge this soon.

i'd review a pullrequest, not commits
